# Tyra Advanced Memory System Configuration
# Production-ready configuration with local-first architecture

# Environment
environment: ${TYRA_ENV:-development}
debug: ${TYRA_DEBUG:-false}
log_level: ${TYRA_LOG_LEVEL:-INFO}

# Server Configuration
server:
  name: "tyra-memory-server"
  version: "1.0.0"
  description: "Advanced MCP memory server with RAG, hallucination detection, and adaptive learning"

  # MCP Protocol Settings
  mcp:
    protocol_version: "2024-11-05"
    capabilities:
      tools: true
      prompts: false
      resources: false
      logging: true

  # Performance Settings
  performance:
    max_concurrent_requests: 10
    request_timeout: 60
    memory_limit_mb: 2048
    enable_metrics: true

# Memory System Configuration
memory:
  # Backend Storage
  backend: "pgvector"

  # Vector Store Configuration
  vector:
    backend: "pgvector"
    dimensions: 1024
    index_type: "hnsw"  # or "ivfflat"
    distance_metric: "cosine"  # cosine, l2, inner_product
    table_name: "memory_embeddings"

    # Index Parameters
    index_params:
      hnsw:
        m: 16
        ef_construction: 64
      ivfflat:
        lists: 100

    # Chunking Settings
    chunking:
      enabled: true
      chunk_size: 512
      chunk_overlap: 50
      respect_boundaries: true

# Database Configurations
databases:
  # PostgreSQL with pgvector
  postgresql:
    host: ${POSTGRES_HOST:-localhost}
    port: ${POSTGRES_PORT:-5432}
    database: ${POSTGRES_DB:-tyra_memory}
    username: ${POSTGRES_USER:-tyra}
    password: ${POSTGRES_PASSWORD:-}

    # Connection Pool
    pool_size: 20
    min_connections: 5
    max_connections: 50
    max_lifetime: 300

    # SSL Configuration
    ssl_mode: ${POSTGRES_SSL_MODE:-prefer}
    ssl_cert: ${POSTGRES_SSL_CERT:-}
    ssl_key: ${POSTGRES_SSL_KEY:-}
    ssl_ca: ${POSTGRES_SSL_CA:-}

  # Redis for Caching
  redis:
    host: ${REDIS_HOST:-localhost}
    port: ${REDIS_PORT:-6379}
    db: ${REDIS_DB:-0}
    password: ${REDIS_PASSWORD:-}

    # Connection Settings
    max_connections: 20
    socket_timeout: 5
    socket_connect_timeout: 5
    retry_on_timeout: true

    # TTL Settings (seconds)
    default_ttl: 3600
    embedding_cache_ttl: 86400
    search_cache_ttl: 1800

# Graph Database Configuration
graph:
  backend: "memgraph"

  # Memgraph Settings
  memgraph:
    host: ${MEMGRAPH_HOST:-localhost}
    port: ${MEMGRAPH_PORT:-7687}
    username: ${MEMGRAPH_USER:-memgraph}
    password: ${MEMGRAPH_PASSWORD:-}
    encrypted: ${MEMGRAPH_ENCRYPTED:-false}
    connection_timeout: 30

    # Graph Features
    temporal_enabled: true
    analytics_enabled: true
    batch_size: 1000

# Embedding Configuration
embeddings:
  # Primary Provider
  primary:
    provider: "huggingface"
    model_name: "sentence-transformers/all-MiniLM-L12-v2"
    device: "auto"  # auto, cpu, cuda:0, etc.
    batch_size: 32
    max_length: 512
    normalize_embeddings: true

    # Performance Settings
    use_fp16: true
    cache_embeddings: true
    warmup_queries: 5

  # Fallback Provider
  fallback:
    provider: "openai"  # Only used if HuggingFace fails
    model_name: "text-embedding-3-small"
    api_key: ${OPENAI_API_KEY:-}
    max_retries: 3
    timeout: 30

# RAG Configuration
rag:
  # Retrieval Settings
  retrieval:
    default_top_k: 20
    rerank_top_k: 5
    min_similarity: 0.3
    max_similarity: 1.0

    # Hybrid Search
    hybrid_enabled: true
    hybrid_weight: 0.7  # Vector vs text search weight

    # Search Strategies
    search_strategies:
      - vector
      - graph
      - hybrid
    default_strategy: "hybrid"

  # Reranking Configuration
  reranking:
    provider: "cross_encoder"
    model_name: "cross-encoder/ms-marco-MiniLM-L-12-v2"
    batch_size: 16
    normalization: "sigmoid"
    cache_enabled: true

  # Hallucination Detection
  hallucination:
    enabled: true
    confidence_levels:
      rock_solid: 95
      high: 80
      fuzzy: 60
      low: 0
    threshold: 75

    # Evidence Analysis
    max_evidence: 10
    evidence_weights:
      similarity: 0.4
      relevance: 0.3
      consistency: 0.3

# Analytics Configuration
analytics:
  enabled: true

  # Performance Tracking
  performance:
    analysis_interval: 300  # 5 minutes
    trend_window_days: 7

    # Alert Thresholds
    alert_thresholds:
      response_time:
        warning: 2.0
        critical: 5.0
      accuracy:
        warning: 0.8
        critical: 0.7
      confidence:
        warning: 0.75
        critical: 0.6
      memory_usage:
        warning: 0.8
        critical: 0.9
      search_relevance:
        warning: 0.7
        critical: 0.6
      hallucination_rate:
        warning: 0.1
        critical: 0.2
      user_satisfaction:
        warning: 0.7
        critical: 0.6
      cost_efficiency:
        warning: 0.8
        critical: 0.7

  # Data Retention
  retention:
    metrics_days: 30
    alerts_days: 30
    recommendations_days: 30

# Adaptive Learning Configuration
adaptation:
  enabled: true

  learning:
    # Experiment Settings
    max_concurrent_experiments: 1
    experiment_duration_minutes: 60
    cycle_interval: 300  # 5 minutes

    # Success Criteria
    min_improvement_threshold: 0.05  # 5%
    rollback_threshold: -0.1  # -10%

    # Strategies
    strategies:
      gradient_descent:
        enabled: true
        learning_rate: 0.1
      bayesian_optimization:
        enabled: true
        acquisition_function: "expected_improvement"
      random_search:
        enabled: true
        exploration_rate: 0.1

    # Adaptable Parameters
    parameters:
      response_time:
        embedding_batch_size: 32
        search_top_k: 20
        rerank_top_k: 5
      quality:
        confidence_threshold: 0.7
        similarity_threshold: 0.6
        hybrid_search_weight: 0.7

# Agent Configuration
agents:
  # Agent Isolation
  isolation:
    enabled: true
    namespace_by_agent: true
    share_entities: false

  # Supported Agents
  supported:
    - tyra
    - claude
    - archon

  # Agent-specific Settings
  agent_configs:
    tyra:
      memory_retention_days: 90
      confidence_threshold: 0.7
      enable_learning: true
    claude:
      memory_retention_days: 30
      confidence_threshold: 0.8
      enable_learning: false
    archon:
      memory_retention_days: 60
      confidence_threshold: 0.75
      enable_learning: true

# Security Configuration
security:
  # Authentication (Future Enhancement)
  auth:
    enabled: false
    type: "none"  # none, api_key, jwt

  # Data Privacy
  privacy:
    encrypt_content: false
    anonymize_logs: true
    data_retention_days: 90

  # Rate Limiting
  rate_limiting:
    enabled: false
    requests_per_minute: 100
    burst_limit: 20

# Logging Configuration
logging:
  level: ${TYRA_LOG_LEVEL:-INFO}
  format: "json"

  # Output Destinations
  outputs:
    console:
      enabled: true
      level: INFO
    file:
      enabled: true
      level: DEBUG
      path: "logs/tyra-memory.log"
      max_size: "100MB"
      backup_count: 5

  # Component Logging
  components:
    memory_manager: INFO
    embedding_provider: INFO
    vector_store: INFO
    graph_engine: INFO
    performance_tracker: INFO
    learning_engine: INFO
    mcp_server: INFO

# Development Settings
development:
  # Hot Reload
  hot_reload: ${TYRA_HOT_RELOAD:-false}

  # Debug Features
  debug_tools:
    enabled: true
    profiling: false
    memory_tracking: false

  # Test Data
  seed_data:
    enabled: false
    samples: 100

# Production Settings
production:
  # Health Checks
  health_checks:
    enabled: true
    interval: 30
    timeout: 10
    endpoints:
      - memory_manager
      - databases
      - embeddings

  # Monitoring
  monitoring:
    metrics_enabled: true
    tracing_enabled: false
    prometheus_port: 9090

  # Scaling
  scaling:
    auto_scale: false
    min_instances: 1
    max_instances: 5
    cpu_threshold: 80
    memory_threshold: 85
