# Provider Configuration
# Defines available providers and their configurations

embeddings:
  providers:
    e5-large:
      class: "src.core.providers.embeddings.huggingface.HuggingFaceProvider"
      config:
        model_name: "intfloat/e5-large-v2"
        device: "cuda"
        trust_remote_code: false
        normalize_embeddings: true
        query_prefix: "query: "
        document_prefix: "passage: "

    all-minilm:
      class: "src.core.providers.embeddings.huggingface.HuggingFaceProvider"
      config:
        model_name: "sentence-transformers/all-MiniLM-L12-v2"
        device: "cpu"
        trust_remote_code: false
        normalize_embeddings: true

    bge-m3:
      class: "src.core.providers.embeddings.huggingface.HuggingFaceProvider"
      config:
        model_name: "BAAI/bge-m3"
        device: "cuda"
        trust_remote_code: true
        normalize_embeddings: true

    openai:
      class: "src.core.providers.embeddings.openai.OpenAIProvider"
      config:
        model_name: "text-embedding-3-small"
        api_key: "${OPENAI_API_KEY}"
        dimensions: 1536

vector_stores:
  providers:
    pgvector:
      class: "src.core.providers.vector_stores.pgvector.PgVectorStore"
      config:
        connection_string: "postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}"
        table_name: "memory_embeddings"
        vector_column: "embedding"
        metadata_column: "metadata"

    qdrant:
      class: "src.core.providers.vector_stores.qdrant.QdrantStore"
      config:
        host: "localhost"
        port: 6333
        collection_name: "tyra_memories"
        vector_size: 1024

    weaviate:
      class: "src.core.providers.vector_stores.weaviate.WeaviateStore"
      config:
        url: "http://localhost:8080"
        class_name: "TyraMemory"

graph_engines:
  providers:
    memgraph:
      class: "src.core.providers.graph_engines.memgraph.MemgraphEngine"
      config:
        host: "localhost"
        port: 7687
        username: "memgraph"
        password: "${MEMGRAPH_PASSWORD}"
        database: "memgraph"


graph_managers:
  providers:
    graphiti:
      class: "src.core.graph.graphiti_integration.GraphitiManager"
      config:
        # LLM Configuration for local vLLM
        llm_base_url: "http://localhost:8000/v1"
        llm_model: "meta-llama/Llama-3.1-70B-Instruct"
        llm_api_key: "dummy-key"
        llm_temperature: 0.1
        llm_max_tokens: 1000
        
        # Embedding Configuration
        embedding_model: "intfloat/e5-large-v2"
        embedding_device: "auto"
        embedding_batch_size: 32
        normalize_embeddings: true
        
        # Reranker Configuration (optional)
        use_reranker: false
        reranker_base_url: "http://localhost:8000/v1"
        reranker_model: "cross-encoder/ms-marco-MiniLM-L-12-v2"
        reranker_api_key: "dummy-key"
        
        # Memgraph Configuration
        memgraph_uri: "bolt://localhost:7687"
        memgraph_username: "memgraph"
        memgraph_password: "${MEMGRAPH_PASSWORD}"
        memgraph_database: "memgraph"
        
        # Temporal Knowledge Graph Configuration
        temporal_features:
          enabled: true
          default_validity_period: 8760  # hours (1 year)
          auto_expire_facts: true
          track_fact_evolution: true
          enable_temporal_queries: true
          
        # Episode Configuration
        episode_config:
          max_episode_length: 10000
          default_episode_type: "memory"
          auto_extract_entities: true
          auto_create_relationships: true
          
        # Graph Optimization
        graph_optimization:
          batch_size: 50
          max_search_results: 100
          search_timeout: 30
          enable_caching: true
          cache_ttl: 3600  # seconds
          
        # Circuit Breaker Configuration
        circuit_breaker:
          failure_threshold: 5
          recovery_timeout: 300  # seconds
          health_check_interval: 60  # seconds

graph_clients:
  providers:
    memgraph:
      class: "src.core.graph.memgraph_client.MemgraphClient"
      config:
        engine_provider: "memgraph"

rerankers:
  providers:
    cross_encoder:
      class: "src.core.providers.rerankers.cross_encoder.CrossEncoderReranker"
      config:
        model_name: "cross-encoder/ms-marco-MiniLM-L-12-v2"
        device: "cuda"
        max_length: 512

    bge_reranker:
      class: "src.core.providers.rerankers.bge.BGEReranker"
      config:
        model_name: "BAAI/bge-reranker-v2-m3"
        device: "cuda"
        use_fp16: true

    cohere:
      class: "src.core.providers.rerankers.cohere.CohereReranker"
      config:
        model_name: "rerank-english-v3.0"
        api_key: "${COHERE_API_KEY}"
